from pathlib import Path

DEFAULT_METADATA_ROOT = Path("/Users/yoonsoo.park/code/ncino/Demo-Master/orgMetadata/main/default/objects")

TIER_1_OBJECTS: list[str] = [
    "Account",
    "Contact",
    "LLC_BI__Loan__c",
    "LLC_BI__Application__c",
    "LLC_BI__Collateral__c",
    "LLC_BI__Collateral_Group__c",
    "LLC_BI__Account_Collateral__c",
    "LLC_BI__Covenant__c",
    "LLC_BI__Account_Covenant__c",
    "LLC_BI__Branch__c",
    "LLC_BI__Product__c",
    "LLC_BI__Product_Line__c",
    "LLC_BI__Product_Type__c",
    "LLC_BI__Connection__c",
    "LLC_BI__Connection_Role__c",
    "LLC_BI__Legal_Entities__c",
    "LLC_BI__Loan_Compliance__c",
    "LLC_BI__Annual_Review__c",
    "LLC_BI__Checklist__c",
    "LLC_BI__AccountDocument__c",
    "LLC_BI__Deposit__c",
    "LLC_BI__Deposit_Product__c",
    "LLC_BI__Address__c",
    "LLC_BI__Loan_Detail__c",
    "LLC_BI__Adverse_Action__c",
    "LLC_BI__Beneficial_Owner__c",
    "LLC_BI__Pricing_Stream__c",
    "LLC_BI__Classification__c",
]

KNOWN_NAMESPACES: dict[str, str] = {
    "LLC_BI": "Core Banking (Loans, Accounts, Compliance)",
    "nFORCE": "UI Framework",
    "nFORMS": "Forms Engine",
    "nSBA": "SBA Lending",
    "FinServ": "Financial Services Cloud",
    "nCRED": "Credit",
    "nDOC": "Document Management",
    "nIQ": "nCino IQ / Analytics",
}

DOMAIN_MAPPING: dict[str, str] = {
    "LLC_BI__Loan__c": "loan-origination",
    "LLC_BI__Application__c": "loan-origination",
    "LLC_BI__Loan_Detail__c": "loan-origination",
    "LLC_BI__Product__c": "loan-origination",
    "LLC_BI__Product_Line__c": "loan-origination",
    "LLC_BI__Product_Type__c": "loan-origination",
    "LLC_BI__Pricing_Stream__c": "loan-origination",
    "LLC_BI__Collateral__c": "collateral-management",
    "LLC_BI__Collateral_Group__c": "collateral-management",
    "LLC_BI__Account_Collateral__c": "collateral-management",
    "LLC_BI__Covenant__c": "credit-management",
    "LLC_BI__Account_Covenant__c": "credit-management",
    "LLC_BI__Classification__c": "credit-management",
    "LLC_BI__Annual_Review__c": "credit-management",
    "LLC_BI__Loan_Compliance__c": "compliance",
    "LLC_BI__Adverse_Action__c": "compliance",
    "LLC_BI__Connection__c": "relationship-management",
    "LLC_BI__Connection_Role__c": "relationship-management",
    "LLC_BI__Legal_Entities__c": "relationship-management",
    "LLC_BI__Beneficial_Owner__c": "relationship-management",
    "LLC_BI__Branch__c": "organization",
    "LLC_BI__Checklist__c": "workflow",
    "LLC_BI__AccountDocument__c": "document-management",
    "LLC_BI__Deposit__c": "deposit-management",
    "LLC_BI__Deposit_Product__c": "deposit-management",
    "LLC_BI__Address__c": "shared",
    "Account": "relationship-management",
    "Contact": "relationship-management",
}
